
---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is cool"
      action:
        run_job_template:
          name: SayHello
          organization: Default
          job_args:
            extra_vars:
              sentence: "{{ event.payload.message }}"
